### PR TITLE
Explicitly document properties that can be null.

### LINKED ISSUE #66: Wrong doc comments
This
```php
return $record->city->name
```

might return `null`. Same with `timeZone`. Probably more.

Doc comment for city says:

>@property string $name The name of the city based on the locales list passed to the constructor. This attribute is returned by all end points.

Should be changed to something like:

>@property string|null $name The name of the city based on the locales list passed to the constructor (null in case the city is unknown). This attribute is returned by all end points.

Also I think it's better to remove all cases of `This attribute is returned by all end points.`
Instead, better only make a note in case the attribute is not supported by all endpoints.

### PR DESCRIPTION
**Pull request by oschwald**
Fixes #66.

### CODE REVIEW

File: src/WebService/Client.php [hunk 1]
```diff
@@ -13,14 +13,14 @@
...
+ * This class provides a client API for all the GeoIP2 Precision web services.
+ * The services are Country, City, and Insights. Each service returns a
+ * different set of data about an IP address, with Country returning the
+ * least data and Insights the most.
  *
- * Each web service end point is represented by a different model class, and
- * these model classes in turn contain multiple Record classes. The record
- * classes have attributes which contain data about the IP address.
+ * Each web service is represented by a different model class, and these model
+ * classes in turn contain multiple Record classes. The record classes have
```
Comment (oalders) [inline src/WebService/Client.php]: Why is Record capitalized here but not in the next sentence?

Comment (oschwald) [inline src/WebService/Client.php]: Not sure. It probably was intended to refer to the namespace specifically, but I agree it is inconsistent. I'll fix it.

Comment (oschwald) [inline src/WebService/Client.php]: 02c5f07
